INSERT INTO COMPANY VALUES (1, 'company1');
INSERT INTO COMPANY VALUES (2, 'company2');
INSERT INTO COMPANY VALUES (3, 'company3');
INSERT INTO COMPANY VALUES (4, 'company4');

INSERT INTO DEPARTMENT VALUES (1, 'Department A');
INSERT INTO DEPARTMENT VALUES (2, 'Department B ');
INSERT INTO DEPARTMENT VALUES (3, 'Department C');
INSERT INTO DEPARTMENT VALUES (4, 'Department D');
INSERT INTO DEPARTMENT VALUES (5, 'Department E');

INSERT INTO POSITION VALUES (1, 'Junior SE');
INSERT INTO POSITION VALUES (2, 'Middle SE');
INSERT INTO POSITION VALUES (3, 'Senior SE');
INSERT INTO POSITION VALUES (4, 'Junior HR');
INSERT INTO POSITION VALUES (5, 'Middle HR');
INSERT INTO POSITION VALUES (6, 'Senior HR');
INSERT INTO POSITION VALUES (7, 'Junior Sales');
INSERT INTO POSITION VALUES (8, 'Middle Sales');
INSERT INTO POSITION VALUES (9, 'Senior Sales');
INSERT INTO POSITION VALUES (10, 'Junior Financier');
INSERT INTO POSITION VALUES (11, 'Middle Financier');
INSERT INTO POSITION VALUES (12, 'Senior Financier');

INSERT INTO USERS VALUES (1, 'Max', 'kolpachev', '1990-05-23', 2, 1);
INSERT INTO USERS VALUES (2, 'Andrey', 'Molchanov', '1980-12-17', 3, 1);
INSERT INTO USERS VALUES (3, 'Sasha', 'Borisov', '1985-8-02', 6, 2);
INSERT INTO USERS VALUES (4, 'Daria', 'Alexeevna', '1995-11-15', 8, 3);
INSERT INTO USERS VALUES (5, 'Yulia', 'Enicheva', '1991-01-09', 9, 3);
INSERT INTO USERS VALUES (6, 'Anton', 'Verbovskii', '1987-08-10', 11, 3);

INSERT INTO COMPANY_DEPARTMENTS VALUES (1, 1);
INSERT INTO COMPANY_DEPARTMENTS VALUES (1, 2);
INSERT INTO COMPANY_DEPARTMENTS VALUES (2, 1);
INSERT INTO COMPANY_DEPARTMENTS VALUES (2, 2);
INSERT INTO COMPANY_DEPARTMENTS VALUES (2, 4);

INSERT INTO USER_DEPARTMENTS VALUES (1, 1);
INSERT INTO USER_DEPARTMENTS VALUES (1, 2);
INSERT INTO USER_DEPARTMENTS VALUES (2, 2);
INSERT INTO USER_DEPARTMENTS VALUES (2, 4);
INSERT INTO USER_DEPARTMENTS VALUES (1, 3);