INSERT INTO COMPANY VALUES (1, 'company1');
INSERT INTO COMPANY VALUES (2, 'company2');
INSERT INTO COMPANY VALUES (3, 'company3');
INSERT INTO COMPANY VALUES (4, 'company4');

INSERT INTO DEPARTMENT VALUES (1, 'Engineering');
INSERT INTO DEPARTMENT VALUES (2, 'Marketing ');
INSERT INTO DEPARTMENT VALUES (3, 'Sales');
INSERT INTO DEPARTMENT VALUES (4, 'Recruitment');
INSERT INTO DEPARTMENT VALUES (5, 'Finance');

INSERT INTO POSITION VALUES (1, 'Junior SE');
INSERT INTO POSITION VALUES (2, 'Middle SE');
INSERT INTO POSITION VALUES (3, 'Senior SE');
INSERT INTO POSITION VALUES (4, 'Junior HR');
INSERT INTO POSITION VALUES (5, 'Middle HR');
INSERT INTO POSITION VALUES (6, 'Senior HR');
INSERT INTO POSITION VALUES (7, 'Junior Sales');
INSERT INTO POSITION VALUES (8, 'Middle Sales');
INSERT INTO POSITION VALUES (9, 'Senior Sales');
INSERT INTO POSITION VALUES (10, 'Junior Financier');
INSERT INTO POSITION VALUES (11, 'Middle Financier');
INSERT INTO POSITION VALUES (12, 'Senior Financier');

INSERT INTO USERS VALUES (1, 'Max', 'kolpachev', '17-05-1990');
INSERT INTO USERS VALUES (1, 'Andrey', 'Molchanov', '04-12-1980');
INSERT INTO USERS VALUES (1, 'Sasha', 'Borisov', '26-02-1995');
INSERT INTO USERS VALUES (1, 'Daria', 'Alexeevna', '03-11-1983');
INSERT INTO USERS VALUES (1, 'Yilia', 'Enicheva', '09-10-1994');
INSERT INTO USERS VALUES (1, 'Anton', 'Verbovskii', '21-08-1987');